{
  imports = [
    ./libs/util.nix
    ./autorandr.nix
    ./bash/module.nix
    ./customscripts.nix
    ./adb.nix
    ./docker.nix
    ./dwm.nix
    ./dunst.nix
    ./experimental.nix
    ./fail2ban.nix
    ./ffsyncserver.nix
    ./flutter.nix
    ./gnomeWM.nix
    ./hyprland.nix
    ./immich.nix
    ./customkbd.nix
    ./kde.nix
    ./kodi.nix
    ./localization.nix
    ./mpv.nix
    ./mysql.nix
    ./netbird-org.nix
    ./nextcloud.nix
    ./nginx.nix
    ./phonecon.nix
    ./python.nix
    ./obsStudio.nix
    ./ollama.nix
    ./qemu.nix
    ./sops.nix
    ./sound.nix
    ./ssh.nix
    ./syncthing.nix
    ./systemd.nix
    ./tailscale.nix
    ./tmux.nix
    ./transmission.nix
    ./vim.nix
    ./xserver.nix
    ./xscreensaver.nix
  ];
}
