{
  imports = [
    ../modules/ssh.nix
    ../modules/autorandr.nix
    ../modules/customscripts.nix
    ../modules/adb.nix
    ../modules/docker.nix
    ../modules/dwm.nix
    ../modules/experimental.nix
    ../modules/ffsyncserver.nix
    ../modules/gnomeWM.nix
    /home/korv/nixos-cfg/modules/hyprland.nix
    ../modules/customkbd.nix
    /home/korv/nixos-cfg/modules/kanata.nix
    ../modules/localization.nix
    ../modules/mysql.nix
    ../modules/nextcloud.nix
    #../modules/packages.nix
    ../modules/phonecon.nix
    ../modules/python.nix
    ../modules/qemu.nix
    ../modules/sound.nix
#   ./modules/sops.nix
    ../modules/syncthing.nix
    ../modules/systemd.nix
    ../modules/ollama.nix
    ../modules/xprofile.nix
    #./nixscripts/helloWorld.nix
    #/home/korv/nixos-cfg/modules/desktopitem.nix
  ];
}
