{
  imports = [
    ../modules/autorandr.nix
    ../modules/customscripts.nix
    ../modules/adb.nix
    ../modules/docker.nix
    ../modules/dwm.nix
    ../modules/dunst.nix
    ../modules/experimental.nix
    ../modules/fail2ban.nix
    ../modules/ffsyncserver.nix
    ../modules/gnomeWM.nix
    ../modules/hyprland.nix
    ../modules/immich.nix
    ../modules/customkbd.nix
    ../modules/kde.nix
    ../modules/kodi.nix
    ../modules/localization.nix
    ../modules/mysql.nix
    ../modules/netbird-org.nix
    ../modules/nextcloud.nix
    #../modules/packages.nix
    ../modules/phonecon.nix
    ../modules/python.nix
    ../modules/obsStudio.nix
    ../modules/ollama.nix
    ../modules/qemu.nix
    #   ./modules/sops.nix
    ../modules/sound.nix
    ../modules/ssh.nix
    ../modules/syncthing.nix
    ../modules/systemd.nix
    ../modules/tmux.nix
    ../modules/transmission.nix
    ../modules/vim.nix
    ../modules/xprofile.nix
    #./nixscripts/helloWorld.nix
  ];
}
