syntax on
set expandtab               "space instead of tabs
set shiftwidth=2
set tabstop=2
set number
"set ignorecase
set smartcase               "ignores case unless search contains uppercase letters

map <F10> :set number!<CR>  "! for toggle, nonumber for off
map <F9> :set rnu!<CR>

noremap <leader>y "+y
noremap <leader>p "+p

set foldmethod=indent
nnoremap <space> za         " toggle folds with spacebar
highlight Folded ctermbg=17
highlight Folded ctermfg=14

"" remaps ""
"all modes:    [ :map, :noremap ]
"normal mode:  [ :nmap, :nnoremap ] 
"visual mode:  [ :vmap, :vnoremap ]
":help recursive_mapping
":help :map-modes
"colors: see /usr/share/vim/vim{version}/syntax/
