source $HOME/.config/vim/settings/commands.vim
  source $HOME/.config/vim/settings/configs.vim
  source $HOME/.config/vim/settings/functions.vim
  source $HOME/.config/vim/settings/mappings.vim
  source $HOME/.config/vim/settings/plugins.vim

function! _colors_in_vim()
  "block comment"
  https://phoenixnap.com/kb/vim-color-schemes
  Example in ~/.config/vim/colors/
  endfunction
function! _modes_in_vim() 
  "block comment"
  all modes:    [ :map, :noremap ]
  normal mode:  [ :nmap, :nnoremap ] 
  visual mode:  [ :vmap, :vnoremap ]
  endfunction
function! _learning_vim() 
  "block comment"
  :help recursive_mapping
  :help :map-modes  
  endfunction
