#!/bin/sh


read='dconf read'
write='dconf write'
keyDir=/com/gexperts/Tilix/quake-hide-lose-focus

preVal=$(${read} ${keyDir})

if [[ $preVal != "false" ]];then
  bool='false'
else
  bool='true'
fi
echo "tilix autohide set to: ${bool}"
$write $keyDir $bool

