ssh-secure: ENC[AES256_GCM,data:/kNAU88+im/JEk+PE6AwnqGNR4JAUH9V7jL5gR/4zM8Dgdjhk3JhlHFxFdOMOS8J56JE9Zr0LJqV/S4cE0miFmK2d0ucsfsweRcfsb5EX/eOl86tlvI+WT3u+uymT+6ssXf+NCwEEgjmU1LresM7m5Lo7vV2r4Gt7KvMkepnIu/pvhINbC0eMY/UWMD7YLAlUJo/w373gayZ5nGW5/o49zTfGPUE3u/Og74uKum8ZDLb8WqznkTSnGGGtWOCKlvpUEA1wK9LgNOKszdW1MpAr+9d9SfTMiDOek1Qx26obZNMY1r4dNtKPhVX+HeJ1SeqjXr8mMwEbcfqfCYeT4GhmdsyIosE9T4Ri6gcPfscAwxDXKKSEqzrAtykl7f/IhGHzidzKklBx1xjC8ie+I98E5iX5BL7zNA8DbKlsmMB8YZr806KF9P1Fb12q2Bbjgzxoh+2poqI+cCDAhw0TOqvVRUaPlgFANn5s+Ld4NP/VibxkQmfiB86DWIBGODTAowr9pErN+tZTePCjtZBf8Py9DFz00Pb3IiWWPaTZlaprN5iDlXVVGDnmvpLl17PMXbVhGiRpKBy7ByFftYgKWIqG6ex/A==,iv:3MIzdf6CTCmuYnMzrkV7BInrIdH7B+Yp5+l1u9jCdvo=,tag:EQtLV/Ue7Fm80jERNDdEaQ==,type:str]
ssh-main: ENC[AES256_GCM,data:qHEqlF/Pj00dHoC1xd73RfZR8FClNNccRzrktLJYIqtorutX86F/ubCd8ZuLcJo1mfe9hLnieFwtM5teIflIfatUgtXemTNo2c8p7xytcu7za6DSMQV5Td4DDzQNOXhie81kDjWGtPmTI3L/B7FqhyTkEl5O+QHt7uTWleYnpJObdLN73O6gL4uGcNW7xf323bWMNBzVqw/7jKfBIT564h+HevljH4IAb+DPaYr74BB/PBY+66AAP7GBx2+JqQv/0KRI/PZHMR9RU40k1qoYVOzUwlpcovCoAhHiJ0zhm5u63wGQxEo/B0/AfZv8NA/0qbZN4co0GYHY255VtLBLoQ7KHfAngxyfLbFC624HXIgEoyX9yRvy61eQyximi/O4hVChKw9Us2QEDcK4c5+wegag5OklMsg1Mi5Kz3f1wBOC1Csd7Av4II/Z50Gt+0P25O5VAJ7cH/FYtbf8afrT7KvkVRkOhA+hvQbjlzcdI+M+x/wzgKZoGGxpx86fmWsJBZATRK65gsxxuTZ7cmLpCiHE91Wqxu/L36uqV+SQT41zu2+NnT4fFFSMHdZpGDwNGT9gWnpy7iqbdSk=,iv:QjYhTYDoDNeA3Ni3X6DwP2TA++G4jXBJXfmVNFjdq+o=,tag:tyuCdLtey/GvqEUaf+lUGw==,type:str]
sops:
    shamir_threshold: 3
    key_groups:
        - hc_vault: []
          age:
            - recipient: age1nqful4cmsa42urdgqhukwgu779kp0qy56fp8rk04h7g00p8t9ywqhrhqhy
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRnVaSDZVOWpCVnZMR2pl
                eVVCTm1KOHRWTkNaU2FVSzhsY3I4LytGZkVBCmtnUVR6am5SNWQ4YllHWG1sSjRN
                c1A5WkdjY0JJZVpsRWZ1ZEYraXZxdUEKLS0tIDUxbFNWMmZITThOMVdWSG9CeTVo
                djRqbk5sU3NzVkRzSUorRlFwNW1UbGcKxCv9/7VHZZX68Cp3fU5h2BAwUdMa7FHw
                P+0frjlELhiN9XNe9f//u8IdPd7T0LZkEQFe1gVhMXz2jumeRQ/NPas=
                -----END AGE ENCRYPTED FILE-----
        - hc_vault: []
          age:
            - recipient: age1fhsz3w7sceap4pclv6488uwedpgewa2m0cva2vyxvjxjnlek9uqsxqgwzl
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqckF1RUJCS2tSM2xyZGFu
                aklud3pKMEM4cVpON0tRZXhJUFpXbTJlRVI4CnhaOHFDOUJUT0grWW02VUxza0Rx
                KytuRldrVVJiRy9mM2pZMmdUaFJMWXMKLS0tIDU3TFp1RHFBeGhFVktxUHBRSERs
                WUpON1RLVVFDRWo5WGNubGZEb0pobHcKGG/F7AN3F14JgrH+LhFvAA0PKzxS13sf
                niw+Fk62VgpgC7pmCIHiZ3rk9q8vZBTAGEM1CgMfd43aknnGQrJBQd4=
                -----END AGE ENCRYPTED FILE-----
        - hc_vault: []
          age:
            - recipient: age15ec4mucxxh6knxk4hydxulwdcs74hvnfca437u3t55yaqecqzussuysfc2
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeWtwVzgwWit4RE9teU5p
                MGpyMGRFYzJDeHBNcDB3Ri9lZmNuY096V1U4Cks0QWd6TFd4cG9zNktlSnJjUkdy
                eGtaRm96OGJRRG1SWnVqbmdVSytIclEKLS0tIDVLR0RielVXMHBoaU4zdHhFb1ZI
                NTNsRkJLTG1RU0o2bVd6V0xjMkRmQU0KTOBp6PlG7P4bE+orlqV+h84HFFigZaHS
                xDO8ZWSd41M6+Cf3Z/smMFY6GdkoKxM3dilt+W83WRR9VQ7tKYJhY2s=
                -----END AGE ENCRYPTED FILE-----
            - recipient: age1n407ytr62p5lw7rsccnkqv7c842jgpvtn9grzf22hruzx5plp9wq07vh72
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTXQ2d3MwMnhDSkpsTE5X
                M21pSG4wSEhpam1ZK0laZW1tYThuNURZWlFBClhVMExrTjROcHZCcVVTczU1N21q
                di9sZTdkelNhSGNpcC9SWkgzNU9nRmcKLS0tIEhQbUlwZnM0N2paM0ZKN29VVm5E
                blZCV2dqaEF1MFh5TVVVY3hnZ2d5NjAKtP/1qlLK2iVlNpXZz6vQuqofAW82f9tn
                x28jProjVjd5UuCCbJ+5DdOmpB765LiUdGeq2JPzdIjL3akIACT1Pao=
                -----END AGE ENCRYPTED FILE-----
            - recipient: age1gac30khqx7rkjpx68pyt77fyh7d50quuukq6cfgjgmnpk3gqyc5qwqp0mt
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaDFwL2pBRmpZcTNGNnl2
                WXZyeFZ0ZTlEdXFFY1ZJN2pDcm9Hc0lDaERvCncrbkRnd0dGQlJIUldxS241OXBq
                Rkk5VTRnYTRtbU1MSVVlRFVPWFdCQVkKLS0tIHlSVFJtZ1ZKYWxJamhJWDF2ZjdY
                SFBPeEtBbnZqSmlBRm51VERSYnpScTQKycbNMaPtWLwsfqaRN9Epw/6QHPMMI2nO
                r5fW5AP2bCzKCHugtKlHMK7Abus8LvP6BPDOs2N8xpeTzMnUznmO4y8=
                -----END AGE ENCRYPTED FILE-----
            - recipient: age18d6sf6rcsv57rtgzpcnpena2lskeu98uj74z4sw3q6lwts02cyms3ha2yh
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZDBTWTl2cXNyaGVoZGFM
                VVpZMmtXdURPUVJjQ1JHeFd4bnJvSHMvczJJCmhObTlydDNrYmc0WEQrQ2p0M2Iy
                NU43U0krME52WElFSUJ6ZDNJNzRaU3cKLS0tIDBmWW1nM3NVbDk3UGcxZUJ4QmZW
                YVFtQ0lrT3JuRVpRdjc4WGxMWHQrTkUKSAns8B5lwAlGdj07rxU5nWqsrOUaWrGB
                lAhGKllzuNUvE8Av51rEnNpqR4IBO0e6tQlKW+sYVt7P5W9PxnqtYxQ=
                -----END AGE ENCRYPTED FILE-----
            - recipient: age1avw28n7f2vymuj5ktuzntjay5l05ls920sgvdev8h3fwuwjc9acqgsuqwp
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2elZYdzFrK2FuRUozSGlS
                VVg5VHBDazZyT256WUg0NzF1Z2lyTEI5NENJClJIRWlKdzh0Nzd5T2ZxUWNZQTBo
                b2xmMnRncldHRHB5SnRrMmdUS1VobTQKLS0tIC9lNHI0cW91YUs5U2FnbzVQcExY
                OG5BU016aU43NHZGVjljZVBJd0hXU00KtszZDPp0dQvl5PXsHxCxMa7pjgJL+aFX
                YMqR76C4zOIycplXTPWIPs7+fQXgwsHvPRsu+zU3b1bWLKkALZdtQW4=
                -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-05T23:36:42Z"
    mac: ENC[AES256_GCM,data:SAsmqdszhiNP8iVv6EYphgSFgRazzwz5Mgr57h0DUDaeozzyQW2ciXdXP7cJlhMWYUw10CB0bJND5JMU5KrkESXt8eZrPSkvB+6B3jhH8ULNMyyjLso94him2j9biNj7TvZJh7gcwoNF9OCQUsdAkqxNUM2nQIAQwHSj81vxYbM=,iv:dMVX59byJ27b71iacH1jwbhkD+yfRCJQhidZy0C5ByU=,tag:p/ysi9B3vsvx0LYsBoAoyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
