keys:
  - &admin age1nqful4cmsa42urdgqhukwgu779kp0qy56fp8rk04h7g00p8t9ywqhrhqhy
  - &system age18d6sf6rcsv57rtgzpcnpena2lskeu98uj74z4sw3q6lwts02cyms3ha2yh
  - &common age1avw28n7f2vymuj5ktuzntjay5l05ls920sgvdev8h3fwuwjc9acqgsuqwp
creation_rules:
  - path_regex: .*json$
    key_groups:
      - age: 
        - *common
      #- age: 
        - *admin
        - *system
  - key_groups:
      - age: 
        - *admin
        - *system
        - *common
