keys:
  - &admin age1nqful4cmsa42urdgqhukwgu779kp0qy56fp8rk04h7g00p8t9ywqhrhqhy
  - &system age18d6sf6rcsv57rtgzpcnpena2lskeu98uj74z4sw3q6lwts02cyms3ha2yh
  - &sysgpg 0df755166b5ee241e63dbb9e413dd6fb29f638ba
  - &sysssh age15ec4mucxxh6knxk4hydxulwdcs74hvnfca437u3t55yaqecqzussuysfc2
  - &labb age1n407ytr62p5lw7rsccnkqv7c842jgpvtn9grzf22hruzx5plp9wq07vh72
  - &common age1avw28n7f2vymuj5ktuzntjay5l05ls920sgvdev8h3fwuwjc9acqgsuqwp
creation_rules:
  - key_groups:
      - age: 
        - *admin
        - *system
        - *common
        - *sysssh
        - *labb
