keys:
  # public key definitions
  - &admin  age1nqful4cmsa42urdgqhukwgu779kp0qy56fp8rk04h7g00p8t9ywqhrhqhy
  - &ruckel age1fhsz3w7sceap4pclv6488uwedpgewa2m0cva2vyxvjxjnlek9uqsxqgwzl
  - &burk   age15ec4mucxxh6knxk4hydxulwdcs74hvnfca437u3t55yaqecqzussuysfc2
  - &labb   age1n407ytr62p5lw7rsccnkqv7c842jgpvtn9grzf22hruzx5plp9wq07vh72
  - &dell   age1gac30khqx7rkjpx68pyt77fyh7d50quuukq6cfgjgmnpk3gqyc5qwqp0mt
  - &system age18d6sf6rcsv57rtgzpcnpena2lskeu98uj74z4sw3q6lwts02cyms3ha2yh
  - &common age1avw28n7f2vymuj5ktuzntjay5l05ls920sgvdev8h3fwuwjc9acqgsuqwp
  - &sysgpg 0df755166b5ee241e63dbb9e413dd6fb29f638ba
creation_rules:
  - path_regex: \.admin
    # at least N key groups needs to be fulfilled
    shamir_threshold: 2
    key_groups:
      # key group 1
      - age:
        - *admin
      # key group 2
      - age:
        - *ruckel
        - *burk
        - *labb
        - *dell
        - *system
        - *common
  - path_regex: \.sensitive
    shamir_threshold: 3
    key_groups:
      - age:
        - *admin
      - age:
        - *ruckel
      - age:
        - *burk
        - *labb
        - *dell
        - *system
        - *common
  # catch-all encryption
  - key_groups:
      - age: 
        - *admin
        - *ruckel
        - *burk
        - *labb
        - *dell
        - *system
        - *common
